[build]
command = "npm install"
publish = "."

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[[scheduled]]
cron = "30 8 * * *"
command = "node index.js"

[[scheduled]]
cron = "0 12 * * *"
command = "node index.js"

[[scheduled]]
cron = "0 17 * * *"
command = "node index.js"

[[scheduled]]
cron = "15 21 * * *"
command = "node index.js"
