[build]
command = "npm install"
publish = "."

[[scheduled]]
cron = "30 8 * * *"
command = "push"

[[scheduled]]
cron = "0 12 * * *"
command = "push"

[[scheduled]]
cron = "0 17 * * *"
command = "push"

[[scheduled]]
cron = "15 21 * * *"
command = "push"
