name: Run Netlify Push Function

on:
  schedule:
    - cron: "30 8 * * *"
    - cron: "0 12 * * *"
    - cron: "0 17 * * *"
    - cron: "15 21 * * *"
  workflow_dispatch:

jobs:
  call-function:
    runs-on: ubuntu-latest
    steps:
      - name: Call Netlify Function
        run: |
          curl -X GET "https://superb-pie-79e20a.netlify.app/.netlify/functions/push"
