name: Push Notifications Cron

on:
  schedule:
    - cron: "0 4 * * *"      # 07:00 GR
    - cron: "0 6 * * *"      # 09:00 GR
    - cron: "0 8 * * *"      # 11:00 GR
    - cron: "0 10 * * *"     # 13:00 GR
    - cron: "0 12 * * *"     # 15:00 GR
    - cron: "0 14 * * *"     # 17:00 GR
    - cron: "0 16 * * *"     # 19:00 GR
    - cron: "0 18 * * *"     # 21:00 GR
    - cron: "0 20 * * *"     # 23:00 GR
    - cron: "30 21 * * *"    # 00:30 GR
  workflow_dispatch:

jobs:
  trigger-push:
    runs-on: ubuntu-latest
    steps:
      - name: Call Netlify Function
        run: |
          curl -X GET "https://superb-pie-79e20a.netlify.app/.netlify/functions/push?t=$(date +%s)"
