name: Push Notifications Cron

on:
  schedule:
    - cron: "0 0 * * *"
    - cron: "0 1 * * *"
    - cron: "0 2 * * *"
    - cron: "0 3 * * *"
    - cron: "0 4 * * *"
    - cron: "0 6 * * *"
    - cron: "0 8 * * *"
    - cron: "0 10 * * *"
    - cron: "0 12 * * *"
    - cron: "0 14 * * *"
    - cron: "0 16 * * *"
    - cron: "30 17 * * *"
  workflow_dispatch:

jobs:
  trigger-push:
    runs-on: ubuntu-latest
    steps:
      - name: Call Netlify Function
        run: |
          curl -X GET "https://superb-pie-79e20a.netlify.app/.netlify/functions/push?t=$(date +%s)"
