name: Push Notifications Cron

on:
  schedule:
    - cron: "20 7 * * *"    # 07:20
    - cron: "30 8 * * *"    # 08:30
    - cron: "0 10 * * *"    # 10:00
    - cron: "0 12 * * *"    # 12:00
    - cron: "30 14 * * *"   # 14:30
    - cron: "30 16 * * *"   # 16:30
    - cron: "42 18 * * *"   # 18:42
    - cron: "15 20 * * *"   # 20:15
    - cron: "30 22 * * *"   # 22:30
  workflow_dispatch:

jobs:
  trigger-push:
    runs-on: ubuntu-latest
    steps:
      - name: Call Netlify Function
        run: |
          curl -X GET "https://superb-pie-79e20a.netlify.app/.netlify/functions/push"
